### ISSUE TITLE
Definir custom urls en un resource

### ISSUE THREAD

**Issue by yukideluxe** [AlfredoRoca/emger#1]
https://github.com/AlfredoRoca/emger/blob/master/config/routes.rb#L28

Ahí has creado el resource emergencies y a continuación le añades al mismo controller dos rutas más. 
Deberías hacerlo así http://guides.rubyonrails.org/routing.html#adding-more-restful-actions

**Comment by AlfredoRoca** [comment]
He movido algún método del controller api al normal y refactorizado algo las rutas.
