### ISSUE TITLE
API no REST y poco personalizable

### ISSUE THREAD

**Issue by yukideluxe** [AlfredoRoca/emger#2]
https://github.com/AlfredoRoca/emger/blob/master/app/controllers/api/v1/emergencies_controller.rb
Creo que podrías conseguir lo mismo que quieres con una API REST (básicamente no haciendo métodos "extra" que no sean `index`, `new`, `create`, `update`, `edit` o `destroy`. 

Por ejemplo en vez de tener action `index` y `index_all` podrías tener solo un action `index` y pasarle parámetros para filtrar por open o tener un orden diferente, así sería la API más personalizable.
El action `here_new_emergency` lo tendrías que conseguir con otro controlador por ejemplo `EmergenciesController` y un resource anidado como lo hicimos en los controladores generales para poner followups en emergencias.

Para que vas a utilizar la API?

**Comment by AlfredoRoca** [comment]
Vemos esto el lunes.
