### ISSUE TITLE
ModbusController

### ISSUE THREAD

**Issue by yukideluxe** [AlfredoRoca/emger#3]
https://github.com/AlfredoRoca/emger/blob/master/app/controllers/modbus_controller.rb
1. Los `require` acostumbran a ir arriba del todo
2. No entiendo porqué las constantes no te funcionan pero, para poner variables de configuración que dependan del environment hay diferentes soluciones. 
   http://stackoverflow.com/questions/1450285/how-to-define-custom-configuration-variables-in-rails
   Mirate la primera y segunda respuesta que explican varias opciones

**Comment by AlfredoRoca** [comment]
Si puedo evitar mas gemas, mejor.
He renombrado y colocado las constantes en config/initializers/modbus_server.rb.
Me falta probar la comunicación con el modbus_server.
